{"version":3,"file":"CanceledError.js","sources":["../../../../../node_modules/axios/lib/cancel/CanceledError.js"],"sourcesContent":["'use strict';\n\nimport AxiosError from '../core/AxiosError.js';\nimport utils from '../utils.js';\n\n/**\n * A `CanceledError` is an object that is thrown when an operation is canceled.\n *\n * @param {string=} message The message.\n * @param {Object=} config The config.\n * @param {Object=} request The request.\n *\n * @returns {CanceledError} The created error.\n */\nfunction CanceledError(message, config, request) {\n  // eslint-disable-next-line no-eq-null,eqeqeq\n  AxiosError.call(this, message == null ? 'canceled' : message, AxiosError.ERR_CANCELED, config, request);\n  this.name = 'CanceledError';\n}\n\nutils.inherits(CanceledError, AxiosError, {\n  __CANCEL__: true\n});\n\nexport default CanceledError;\n"],"names":["CanceledError","message","config","request","AxiosError","call","this","ERR_CANCELED","name","utils","inherits","__CANCEL__"],"mappings":"gEAcA,SAASA,EAAcC,EAASC,EAAQC,GAEtCC,EAAWC,KAAKC,KAAiB,MAAXL,EAAkB,WAAaA,EAASG,EAAWG,aAAcL,EAAQC,GAC/FG,KAAKE,KAAO,gBAGdC,EAAMC,SAASV,EAAeI,EAAY,CACxCO,YAAY"}